apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-03-20T00:04:27Z"
  generateName: appy-helm-guestbook-b54fd65b-
  labels:
    app: helm-guestbook
    pod-template-hash: b54fd65b
    release: appy
  name: appy-helm-guestbook-b54fd65b-8fgz7
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: appy-helm-guestbook-b54fd65b
    uid: 0a90e6d9-ac04-4a83-b453-2e9dc1523473
  resourceVersion: "5929"
  selfLink: /api/v1/namespaces/default/pods/appy-helm-guestbook-b54fd65b-8fgz7
  uid: c1334eec-57d6-4a8d-a4f3-5511757040e9
spec:
  containers:
  - image: sethsil/demo:latest
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: helm-guestbook
    ports:
    - containerPort: 3000
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-frgc2
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-frgc2
    secret:
      defaultMode: 420
      secretName: default-token-frgc2
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-03-20T00:04:27Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-03-20T00:04:27Z"
    message: 'containers with unready status: [helm-guestbook]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-03-20T00:04:27Z"
    message: 'containers with unready status: [helm-guestbook]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-03-20T00:04:27Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://b7df05a858b9f34abaf51153ad0e3977ce287c8577fe608c25ae52ec09027d67
    image: sethsil/demo:latest
    imageID: docker-pullable://sethsil/demo@sha256:4eec7ea68c554f0ccd8ecd10112b6ef715c61460e69fe24c9425710fe5001c06
    lastState:
      terminated:
        containerID: docker://4b89389549571f752fa86aba74735814c349590b88c7b050626a1578426dd897
        exitCode: 0
        finishedAt: "2020-03-20T00:06:54Z"
        reason: Completed
        startedAt: "2020-03-20T00:06:24Z"
    name: helm-guestbook
    ready: false
    restartCount: 5
    state:
      running:
        startedAt: "2020-03-20T00:07:38Z"
  hostIP: 192.168.65.3
  phase: Running
  podIP: 10.1.0.12
  qosClass: BestEffort
  startTime: "2020-03-20T00:04:27Z"
